name: Build Lab3

on:
  push:
    paths:
      - 'Lab3/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'  
      - run: dotnet build Lab3/Lab3
