name: Compile report 2 and upload

on:
  push:
    paths:
      - 'Reports/Lab2**'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd Reports
          docker run -v "$(pwd):/data" pandoc/latex --defaults=Lab2/defaults.yaml

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lab2_report
          path: Reports/AA_21-22_report2.pdf
