name: Compile report and upload

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd Report
          docker run -v "$(pwd):/data" pandoc/latex --defaults=defaults.yaml

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: Report/AA_21-22_report.pdf
